// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/worker.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Cipher        []byte                 `protobuf:"bytes,3,opt,name=cipher,proto3" json:"cipher,omitempty"`
	Mac           []byte                 `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardEnvelope) Reset() {
	*x = ShardEnvelope{}
	mi := &file_api_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardEnvelope) ProtoMessage() {}

func (x *ShardEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardEnvelope.ProtoReflect.Descriptor instead.
func (*ShardEnvelope) Descriptor() ([]byte, []int) {
	return file_api_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ShardEnvelope) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardEnvelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ShardEnvelope) GetCipher() []byte {
	if x != nil {
		return x.Cipher
	}
	return nil
}

func (x *ShardEnvelope) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

type StorageStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCapacity int64                  `protobuf:"varint,2,opt,name=total_capacity,json=totalCapacity,proto3" json:"total_capacity,omitempty"`
	UsedCapacity  int64                  `protobuf:"varint,3,opt,name=used_capacity,json=usedCapacity,proto3" json:"used_capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageStats) Reset() {
	*x = StorageStats{}
	mi := &file_api_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStats) ProtoMessage() {}

func (x *StorageStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStats.ProtoReflect.Descriptor instead.
func (*StorageStats) Descriptor() ([]byte, []int) {
	return file_api_worker_proto_rawDescGZIP(), []int{1}
}

func (x *StorageStats) GetTotalCapacity() int64 {
	if x != nil {
		return x.TotalCapacity
	}
	return 0
}

func (x *StorageStats) GetUsedCapacity() int64 {
	if x != nil {
		return x.UsedCapacity
	}
	return 0
}

type ShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardRequest) Reset() {
	*x = ShardRequest{}
	mi := &file_api_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRequest) ProtoMessage() {}

func (x *ShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRequest.ProtoReflect.Descriptor instead.
func (*ShardRequest) Descriptor() ([]byte, []int) {
	return file_api_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ShardRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_worker_proto_rawDescGZIP(), []int{3}
}

func (x *PingRequest) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

var File_api_worker_proto protoreflect.FileDescriptor

const file_api_worker_proto_rawDesc = "" +
	"\n" +
	"\x10api/worker.proto\x12\n" +
	"rpc.worker\"j\n" +
	"\rShardEnvelope\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x16\n" +
	"\x06cipher\x18\x03 \x01(\fR\x06cipher\x12\x10\n" +
	"\x03mac\x18\x04 \x01(\fR\x03mac\"Z\n" +
	"\fStorageStats\x12%\n" +
	"\x0etotal_capacity\x18\x02 \x01(\x03R\rtotalCapacity\x12#\n" +
	"\rused_capacity\x18\x03 \x01(\x03R\fusedCapacity\")\n" +
	"\fShardRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"!\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping2\xc9\x01\n" +
	"\x06Worker\x12A\n" +
	"\n" +
	"StoreShard\x12\x19.rpc.worker.ShardEnvelope\x1a\x18.rpc.worker.StorageStats\x12A\n" +
	"\n" +
	"FetchShard\x12\x18.rpc.worker.ShardRequest\x1a\x19.rpc.worker.ShardEnvelope\x129\n" +
	"\x04Ping\x12\x17.rpc.worker.PingRequest\x1a\x18.rpc.worker.StorageStatsB\x10Z\x0epkg/rpc/workerb\x06proto3"

var (
	file_api_worker_proto_rawDescOnce sync.Once
	file_api_worker_proto_rawDescData []byte
)

func file_api_worker_proto_rawDescGZIP() []byte {
	file_api_worker_proto_rawDescOnce.Do(func() {
		file_api_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_worker_proto_rawDesc), len(file_api_worker_proto_rawDesc)))
	})
	return file_api_worker_proto_rawDescData
}

var file_api_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_worker_proto_goTypes = []any{
	(*ShardEnvelope)(nil), // 0: rpc.worker.ShardEnvelope
	(*StorageStats)(nil),  // 1: rpc.worker.StorageStats
	(*ShardRequest)(nil),  // 2: rpc.worker.ShardRequest
	(*PingRequest)(nil),   // 3: rpc.worker.PingRequest
}
var file_api_worker_proto_depIdxs = []int32{
	0, // 0: rpc.worker.Worker.StoreShard:input_type -> rpc.worker.ShardEnvelope
	2, // 1: rpc.worker.Worker.FetchShard:input_type -> rpc.worker.ShardRequest
	3, // 2: rpc.worker.Worker.Ping:input_type -> rpc.worker.PingRequest
	1, // 3: rpc.worker.Worker.StoreShard:output_type -> rpc.worker.StorageStats
	0, // 4: rpc.worker.Worker.FetchShard:output_type -> rpc.worker.ShardEnvelope
	1, // 5: rpc.worker.Worker.Ping:output_type -> rpc.worker.StorageStats
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_worker_proto_init() }
func file_api_worker_proto_init() {
	if File_api_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_worker_proto_rawDesc), len(file_api_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_worker_proto_goTypes,
		DependencyIndexes: file_api_worker_proto_depIdxs,
		MessageInfos:      file_api_worker_proto_msgTypes,
	}.Build()
	File_api_worker_proto = out.File
	file_api_worker_proto_goTypes = nil
	file_api_worker_proto_depIdxs = nil
}
